name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: cd ./server && npm install
    - run: cd ./server && ./node_modules/.bin/pkg ./server.js --node --out-path ./build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: server/build/
        asset_name: app
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
